### ISSUE TITLE
Improve SetClass situation.

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-js-dom#12]
Currently, the documentation has this example:

```Go
d := dom.GetWindow().Document()
e1 := d.GetElementByID("#my-element")
e2 := d.GetElementByID("#my-element")

e1.SetClass("some-class")
println(e1.Class().String() == e2.Class().String())
```

That will not compile because `Element` interface does not have `SetClass` method exposed. So, to access the `SetClass` method of `BasicElement` struct, one needs to go the long way:

```Go
var e dom.HTMLDivElement
e.BasicHTMLElement.BasicElement.SetClass()
```

Or, if you only have an interface like `HTMLElement` given to you, getting to `SetClass` is impossible without lots of type assertions.

The example should be rewritten to use correct code that works, for example:

```Go
d := dom.GetWindow().Document()
e1 := d.GetElementByID("#my-element")
e2 := d.GetElementByID("#my-element")

e1.Class().SetString("some-class")
println(e1.Class().String() == e2.Class().String())
```

And since the `SetClass` method of `BasicElement` struct is redundant, and effectively unusable, it might as well be removed.

---

Separately, the interface of `TokenList` can be improved. Currently, it offers separate methods to set a single string and set a slice:

```Go
Set(s []string)
SetString(s string)
```

I would suggest you consider changing/adding a method with the signature:

```Go
Set(s ...string)
```

It's shorter, one method, and can be used in all situations:

```
e.Set("single-class")
e.Set("class-a", "class-b", "class-c")

var classes = []string{"foo", "bar"}
e.Set(classes...)
```

### Summary

- [x] Fix documentation by providing valid code.
- [ ] ~~Remove unnecessary `SetClass()` method.~~
- [x] Consider a better signature for setting `TokenList` values.

**Comment by shurcooL** [comment]
I am in agreement with your decision in points two and three for now, you provide convincing arguments.

Point one still needs to be addressed.

**Comment by dominikh** [comment]
@shurcooL Please review https://github.com/dominikh/go-js-dom/compare/class
