### ISSUE TITLE
Do not truncate accuracy of values for various positions/dimension methods.

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-js-dom#19]
### Motivation

Using `int` for those x/y positions/widths/heights truncates the accuracy of returned values (to nearest int). This is not acceptable in some situations. Consider that browsers may have their zoom level set to something like 90% or 125%, so positions/widths may often end up being non-integer even if they are integer in source HTML.

This fixes a real/testable bug in my code where getting the current window position and restoring it later resulted in a minor drift. Switching to `float64` fixes it.

I see some APIs already use `float64`, like `OffsetTop()`, `OffsetWidth()`. I propose all other similar APIs should be changed from `int` to `float64`.

### Sample Patch

This is a sample patch that I used to test if this would work. It did work. It's an MVP patch that doesn't change all similar APIs, only the ones I needed to run my trial.

```patch
From 87d66042d174ce83a0c2a5984c17e8e55965dd75 Mon Sep 17 00:00:00 2001
From: Dmitri Shuralyov <shurcooL@gmail.com>
Date: Sun, 19 Apr 2015 21:57:54 -0700
Subject: [PATCH] WIP: Try out float64 precision for positions and dimensions.

This is an MVP test to see if it makes a difference in fixing slight
drift when saving/restoring window scroll position, etc.
---
 dom.go | 28 ++++++++++++++--------------
 1 file changed, 14 insertions(+), 14 deletions(-)

diff --git a/dom.go b/dom.go
index 7ed4e42..18f3200 100644
--- a/dom.go
+++ b/dom.go
@@ -809,14 +809,14 @@ type Window interface {
 	Location() *Location
 	Name() string
 	SetName(string)
-	InnerHeight() int
-	InnerWidth() int
+	InnerHeight() float64
+	InnerWidth() float64
 	Length() int
 	Opener() Window
 	OuterHeight() int
 	OuterWidth() int
-	ScrollX() int
-	ScrollY() int
+	ScrollX() float64
+	ScrollY() float64
 	Parent() Window
 	ScreenX() int
 	ScreenY() int
@@ -852,7 +852,7 @@ type Window interface {
 	Scroll(x, y int)
 	ScrollBy(dx, dy int)
 	ScrollByLines(int)
-	ScrollTo(x, y int)
+	ScrollTo(x, y float64)
 	SetCursor(name string)
 	SetInterval(fn func(), delay int) int
 	SetTimeout(fn func(), delay int) int
@@ -890,12 +890,12 @@ func (w *window) SetName(s string) {
 	w.Set("name", s)
 }
 
-func (w *window) InnerHeight() int {
-	return w.Get("innerHeight").Int()
+func (w *window) InnerHeight() float64 {
+	return w.Get("innerHeight").Float()
 }
 
-func (w *window) InnerWidth() int {
-	return w.Get("innerWidth").Int()
+func (w *window) InnerWidth() float64 {
+	return w.Get("innerWidth").Float()
 }
 
 func (w *window) Length() int {
@@ -914,12 +914,12 @@ func (w *window) OuterWidth() int {
 	return w.Get("outerWidth").Int()
 }
 
-func (w *window) ScrollX() int {
-	return w.Get("scrollX").Int()
+func (w *window) ScrollX() float64 {
+	return w.Get("scrollX").Float()
 }
 
-func (w *window) ScrollY() int {
-	return w.Get("scrollY").Int()
+func (w *window) ScrollY() float64 {
+	return w.Get("scrollY").Float()
 }
 
 func (w *window) Parent() Window {
@@ -1065,7 +1065,7 @@ func (w *window) ScrollByLines(i int) {
 	w.Call("scrollByLines", i)
 }
 
-func (w *window) ScrollTo(x, y int) {
+func (w *window) ScrollTo(x, y float64) {
 	w.Call("scrollTo", x, y)
 }
 
-- 
2.3.2 (Apple Git-55)

```

**Comment by dominikh** [comment]
Are you sure that this is true for all relevant browsers? Element.clientHeight for Firefox is documented to truncate to ints, for example. I couldn't find anything about the methods on Window, though.

The ClientRect type should be changed, however. That one does support floats.

**Comment by shurcooL** [comment]
> Are you sure that this is true for all relevant browsers?

I am not sure. I just did one ad-hoc test with latest stable Chrome, and I did not read docs on the underlying types. I just know `js.Object.Float()` will work even if the underlying number has an "integer value".

Those considerations should be applied for the real PR that closes this.

However, it seems better to expose float64s for values that make sense as floating point, even if some browser implementations may currently only expose integer accuracy. For example, things like positions, widths, heights make sense as floats. Counts, lengths, etc. make sense as ints.

As I mentioned above, I think considering 90% zoom level in a browser will help expose a lot of float values that would otherwise appear as ints.

> The ClientRect type should be changed, however. That one does support floats.

Yep, that one is definitely a candidate for upgrade to floats.

I'd expect the same for funcs related to window scroll position, and maybe more.

**Comment by shurcooL** [comment]
Hi @dominikh,

Is there any progress on this? Can I do something to help?

**Comment by dominikh** [comment]
No progress so far. I haven't had the time to conduct the necessary research, nor make up my mind about breaking many users of the package. I'm also not clear on which parts of the API exactly would be affected. Your only concrete example was Window. What other APIs do we have that currently return ints but should be returning floats?

http://stackoverflow.com/questions/3603065/how-to-make-jquery-to-not-round-value-returned-by-width and http://stackoverflow.com/questions/11907514/getting-the-actual-floating-point-width-of-an-element would suggest that our current behaviour, at least for elements, is correct and in line with what e.g. JQuery is doing.

For elements, the canonical solution seems to be using ClientRect, in which case we'd only have to fix that one. See http://jsfiddle.net/Z2MBj/173/ for a comparison with JQuery or http://jsfiddle.net/Z2MBj/174/ for plain JavaScript. Also, https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth documents Element.clientWidth to return integers, not floats. But apparently we're not implementing Element.clientWidth in js/dom at all currently.

If you want to help, find some authoritative source stating that the various methods on Window should return floats. I don't think we have to do anything for types other than Window and ClientRect.

**Comment by shurcooL** [comment]
Window includes scroll methods, right?

**Comment by dominikh** [comment]
Yes.

**Comment by shurcooL** [comment]
Ok, after looking a little closer, I have some additional observations. I plan to look more thoroughly in the future.

- MDN docs on Window API (https://developer.mozilla.org/en-US/docs/Web/API/Window) don't seem to specify anything about the precision or type used for scrollY, innerWidth, etc.

- As you mentioned, https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth seems to clearly suggest that `getBoundingClientRect()` returns fractional values, yet its own page https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect doesn't really say that.

- After trying stuff in Chrome Stable on OS X, I could not get Window.InnerWidth to ever return anything but an integer.

- After trying stuff in Chrome Stable on OS X, I could only get Window.ScrollY to ever return float values when page zoom is something other than 100%.

- When trying stuff in Firefox Developer Edition on OS X, I could not reproduce neither Window.InnerWidth nor Window.ScrollY as anything but integer values regardless of browser zoom, even when scrolling via trackpad with inertia and all that.

- The above suggests to me that Chrome returning floating values for ScrollY under non-100% zoom levels may be a "bug", or at least it's not the most common behavior. If so, this is kinda great news, because dom doesn't need to be changed (at least the `Window` interface), and integers are simpler, more precise and nicer to work with than floats.

**Comment by shurcooL** [comment]
@dominikh, can you explain why https://godoc.org/honnef.co/go/js/dom#HTMLElement.OffsetHeight (and all Offset methods of HTMLElement interface) return `float64`? It doesn't seem to be documented as either integer or floating point values at https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement, but in my local testing I could only get integer values.

I think those methods returning `float64` is what drove me to try converting everything to `float64`, because I had code like this:

```Go
dom.GetWindow().ScrollTo(dom.GetWindow().ScrollX(), target.OffsetTop()+target.OffsetHeight())
```

And it makes sense for a consistent type to be used (`float64` or `int`).

**Comment by shurcooL** [comment]
> @dominikh, can you explain why https://godoc.org/honnef.co/go/js/dom#HTMLElement.OffsetHeight (and all Offset methods of HTMLElement interface) return `float64`? It doesn't seem to be documented as either integer or floating point values at https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement, but in my local testing I could only get integer values.

My apologies, I was blind to the keywords `double` (I was scanning for floats and integers):

> `HTMLElement.offsetHeight`
> Returns a double containing the height of an element, relative to the layout.
