### ISSUE TITLE
moving under gopherjs organization?

### ISSUE THREAD

**Issue by slimsag** [dominikh/go-js-dom#21]
Heya @dominikh ! This is a really broad open-ended question (feel free to ignore / close if you like).. just wondering if you've considered placing this project under e.g. `github.com/gopherjs/dom` or something? I think that would help with discovery a bit, as the first place I looked for this was in that organization.

If you dislike the idea / it's already been discussed etc. then I apologize for bringing it up -- I just think it's a nice project and really central to the needs of most gopherjs users and wondered if you'd considered it before or not. (obviously I can't speak for gopherjs maintainers either).

Either way, great package! Cheers!

**Comment by dominikh** [comment]
Short answer, quoting myself from earlier this year:

> It's not part of the GopherJS organization because I believe in an open and independent ecosystem and don't think that everything GopherJS-related has to live in that organisation.

Longer answer: I consider `js/dom` *my* project. I'm the only gatekeeper (person who can accept changes, make final decisions and so on). Projects in organisations, on the other hand, are joint projects where multiple people (optimally a large subset of the people involved in the organisation) have equal voices. And that's fine for certain projects, but I think it's the wrong approach for libraries such as this one.

I think it would be wrong to consider, or even push, `js/dom` as the "official" DOM bindings for GopherJS. They're probably the de facto standard ones right now, but they should be so on their own merit. If someone else comes up with a way better alternative one day, its success shouldn't be hindered by the fact that it's a "3rd party", while mine would be "official" or "endorsed".

I know that not everyone shares my opinion on this and would probably prefer if `js/dom` was part of the GopherJS organization. However, it's probably too late to make that decision now, anyway. If it were moved to the organisation, it should probably lose its vanity import path (`honnef.co/go/js/dom`) and instead be `github.com/gopherjs/dom` or something similar. That, however, would break a lot of existing code.

I hope this clears up why it's the way it is.

**Comment by slimsag** [comment]
Yep, that clears up all my questions! It sounds like you've already thought it all through and found it to not be the correct choice, and I trust your judgement here. I appreciate the prompt and descriptive answer @dominikh :smile:
