### ISSUE TITLE
Feature Request: Element.SetOuterHTML.

### ISSUE THREAD

**Issue by shurcooL** [dominikh/go-js-dom#30]
The `Element` interface has `InnerHTML` and `SetInnerHTML` but no equivalents for `outerHTML`.

https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML

Is there a reason? Is `outerHTML` not a first class citizen or is there another reason why it should not be supported unlike `innerHTML`?

If there's no reason to avoid adding it, I think it'd be useful. I've been doing:

```Go
e.Underlying().Set("outerHTML", html)
```

One time I accidentally used the wrong variable (type `int` rather than `string`), and the static type check didn't catch it because `js.Object.Set` accepts `interface{}`. If I could've used `SetOuterHTML`, it'd be caught and save me time (and other people who might make a mistake of this class in the future).

**Comment by dominikh** [comment]
It's not part of js/dom because the MDN lists Element.outerHTML as an "experimental API that should not be used in production code." – We generally don't add experimental APIs to this package.

**Comment by shurcooL** [comment]
Where do you see that? I can't find that string on the page I linked.

I don't see anything saying "experiment" here either:

https://w3c.github.io/DOM-Parsing/#widl-Element-outerHTML

**Comment by dominikh** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element: 
![2016-01-26_04h-32m-14s](https://cloud.githubusercontent.com/assets/39825/12571885/f693dc30-c3e5-11e5-82c3-af6fb23e1719.png)

**Comment by dominikh** [comment]
Though frankly I do not comprehend the w3c landscape, their "living standards" and why outerHTML is labelled experimental.

**Comment by dominikh** [comment]
Fixed in e00d5ec03f9f2c6834826c3be6cf8b13d0a5f5df.

**Comment by shurcooL** [comment]
Thanks!
