### ISSUE TITLE
createShadowRoot() and WebComponent

### ISSUE THREAD

**Issue by Slaals** [dominikh/go-js-dom#33]
Hi,

Is it possible to use `createShadowRoot()`? If not, do you plan to bind `createShadowRoot` and everything related to Web components? That would be great and useful for the comunity I guess.

**Comment by dominikh** [comment]
I have no plans for adding support for web components to js/dom myself. I would, however, accept contributions that add the missing bits, given that they're well designed.

**Comment by Slaals** [comment]
@dominikh Ok, thank you. I'll work on it then. You can close this issue.
