### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dragosbulugean** [dominikh/go-js-dom#34]
I have: Go 1.7.1, GopherJS 1.7-1.
Can't figure out why i'm receiving: Uncaught RangeError: Maximum call stack size exceeded.
Is it a bug somewhere?

```go
package main

import "honnef.co/go/js/dom"

func main() {
	d := dom.GetWindow().Document()
	h := d.GetElementByID("app")

	h.AddEventListener("click", false, func(event dom.Event) {
		event.PreventDefault()
		h.SetInnerHTML("I am Clicked")
		println("This message is printed in browser console")
	})
}
```

It's the $internalize function producing this error by repeatedly calling the searchJsObject function.

**Comment by dragosbulugean** [comment]
Applying this method:
```go
import "github.com/gopherjs/gopherjs/js"

element := js.Global.Get("document").Call("getElementById", "foo")
element.Set("onclick", func(event *js.Object) {
      /* do something to handle click event */
})
```
or 

``` go
import "github.com/gopherjs/gopherjs/js"

element := js.Global.Get("document").Call("getElementById", "foo")
element.Call("addEventListener", "click", func(event *js.Object) {
      /* do something to handle click event */
})
```
results in the same error message, so I'm afraid this might be a bug for GopherJS

**Comment by dragosbulugean** [comment]
Alright, here's what happened.
I use glide for managing go packages at a project level. I had github.com/gopherjs/gopher.js installed my vendor by glide. That was a problem. Somehow, Gopherjs recompiled part of itself into JS if that makes any sense, and things get tangled resulting in this incredible recursion. So neither dom nor Gopherjs is to blame. 
I will close issue. Thanks!

**Comment by shurcooL** [comment]
Yes, GopherJS currently does not support being vendored. This is issue https://github.com/gopherjs/gopherjs/issues/415.

**Comment by dragosbulugean** [comment]
good to know!
