### ISSUE TITLE
Accessing Values From Input Forms

### ISSUE THREAD

**Issue by pggsx** [dominikh/go-js-dom#38]
Based on documentation it looks be that you would have to use HTML input events to gather information from input fields. Is there no  golang alternative to using a .value in JS terms?

**Comment by shurcooL** [comment]
> Based on documentation

Which documentation are you referring to?

> use HTML input events

Do you mean, in a callback for "input" events, you want to access the input value?

> Is there no golang alternative to using a .value in JS terms?

Are you referring to the `value` field of an HTML input element?

If so, there is one:

https://godoc.org/honnef.co/go/js/dom#HTMLInputElement.Value

**Comment by pggsx** [comment]
That's exactly what I was looking for lol! Thanks!
