### ISSUE TITLE
CanvasRenderingContext2D.DrawImage doesn't accept *HTMLImageElement because its parameter is *Element.

### ISSUE THREAD

**Issue by Luncher** [dominikh/go-js-dom#48]
`dom.CanvasRenderingContext2D` type has a drawImage method, but can not input `dom.HTMLImageElement` parameter

**Comment by shurcooL** [comment]
`drawImage` is documented at https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage. It describes the `image` parameter like so:

> An element to draw into the context. The specification permits any canvas image source (`CanvasImageSource`), specifically, a `CSSImageValue`, an `HTMLImageElement`, an `SVGImageElement`, an `HTMLVideoElement`, an `HTMLCanvasElement`, an `ImageBitmap`, or an `OffscreenCanvas`.

`HTMLImageElement` is listed there and should work.

> but can not input `dom.HTMLImageElement` parameter

Sorry, I don't understand. Can you clarify? Is there a bug in `dom` package?

**Comment by Luncher** [comment]
The drawImage method does not support HTMLImageElement as a parameter

**Comment by dominikh** [comment]
@shurcooL For some reason (790c7894 to be specific), some of those CanvasRenderingContext2D methods are accepting `*Element`, a pointer to an interface, which should definitely not be the case.

**Comment by shurcooL** [comment]
Thanks for pointing that out. That looks like an oversight during #44. We should resolve it by changing the signature to accept `Element` interface, I think the breaking API change is warranted.

**Comment by luckcolors** [comment]
Welp my fault.

**Comment by shurcooL** [comment]
@luckcolors No problem. It can be more efficient to quickly spot issues when actually using the code to do something, rather than spending too much time trying to catch all issues during code review. I've made PR #49 to resolve it, feel free to look.
