### ISSUE TITLE
Using HTML5 history gives a nil reference error

### ISSUE THREAD

**Issue by grkuntzmd** [dominikh/go-js-dom#56]
When I run
```go
println(dom.GetWindow().History().Length())
```
I get the error
```
Uncaught Error: runtime error: invalid memory address or nil pointer dereference
```
but if I use
```go
println(js.Global.Get("history").Get("length"))
```
the output is "2", as expected, both running in Chrome Version 66.0.3359.181 (Official Build) (64-bit), the latest version.

**Comment by shurcooL** [comment]
This is because `window.History()` is not implemented, see #41.
