### ISSUE TITLE
"go get -u honnef.co/go/js/dom" fails

### ISSUE THREAD

**Issue by h8liu** [dominikh/go-js-dom#58]
the https cert at honnef.co has expired.

**Comment by shurcooL** [comment]
Thanks for reporting @h8liu! I suspect we’ll have this fixed within 12 hours. /cc @dominikh

In the meantime, if someone doesn’t have this package and needs to clone it, a workaround is possible:

```
mkdir -p $GOPATH/src/honnef.co/go/js
cd $GOPATH/src/honnef.co/go/js
git clone https://github.com/dominikh/go-js-dom dom
```

**Comment by dominikh** [comment]
The issue should be resolved now. I'm so sorry for the inconvenience :/
