### ISSUE TITLE
CreateTextNode() panics

### ISSUE THREAD

**Issue by antong** [dominikh/go-js-dom#76]
I am trying to use CreateTextNode() with GOOS=js GOARCH=wasm and go1.13.9.

```
// +build js
package main

import "honnef.co/go/js/dom/v2"

func main() {
	d := dom.GetWindow().Document().(dom.HTMLDocument)
	_ = d.CreateTextNode("foobar")
}
```

The above code panics with:
```
panic: interface conversion: dom.Node is dom.Text, not *dom.Text wasm_exec.js:41:14
<empty string> wasm_exec.js:41:14
goroutine 1 [running]: wasm_exec.js:41:14
honnef.co/go/js/dom/v2.document.CreateTextNode(0xc1e018, 0xbade2, 0x6, 0x108be48) wasm_exec.js:41:14
	/go/pkg/mod/honnef.co/go/js/dom/v2@v2.0.0-20190526011328-ebc4cf92d81f/dom.go:803 +0x9 wasm_exec.js:41:14
main.main() wasm_exec.js:41:14
	/tmp/godomtest/main.go:10 +0xc wasm_exec.js:41:14
exit code: 2 wasm_exec.js:106:14
```

**Comment by antong** [comment]
I readily admit that I have no DOM experience whatsoever, so I may be misunderstanding everything. The way I ran into this, was when I tried to construct something like `<li><span>Some text</span> some more text.</li>`. The way I figured this would be done is to make a LI element, make a SPAN element and then LI.AppendChild(SPAN) and then txt := CreateTextNode(" some more text.") and LI.AppendChild(txt).

**Comment by dmitshur** [comment]
Thanks for reporting this @antong. This is a bug in the `wrapNode` function. What you were doing is valid and should work once we fix this bug.

The fix is:

```diff
--- a/v2/dom.go
+++ b/v2/dom.go
@@ -239,7 +239,7 @@ func wrapNode(o js.Value) Node {
        switch elementConstructor(o) {
        // TODO all the non-element cases
        case js.Global().Get("Text"):
-               return Text{&BasicNode{o}}
+               return &Text{&BasicNode{o}}
        default:
                return wrapElement(o)
        }
```

I'll mention that other approaches to setting inner content of HTML elements include:

1.	By setting the `textContent` property:

	```Go
	span := document.CreateElement("span").(*dom.HTMLSpanElement)
	span.SetTextContent("Some text")
	document.Body().AppendChild(span)
	```

2. By setting the `innerHTML` property:

	```Go
	li := document.CreateElement("li").(*dom.HTMLLIElement)
	li.SetInnerHTML("<span>Some text</span> some more text.")
	document.Body().AppendChild(li)
	```

As another aside, you wrote:

```Go
// +build js
package main
```

Keep in mind there needs to be a blank line between the build constraint comment and the package clause, otherwise it becomes a package comment rather than a build constraint.

**Comment by antong** [comment]
Thank you for verifying and for the support in providing workarounds! Yes, the build constraint was a bug in the description. Thanks!
